import Link from "next/link";
import Section from "@/components/Section";
import Globe from "@/components/Globe";
const industries=["Logistics","Warehousing","Manufacturing","Construction","Hospitality","Agriculture","Food Production","Automotive","Retail","Cleaning Services","Facility Management"];
const process=[["01","Consultation"],["02","Workforce Planning"],["03","Talent Sourcing"],["04","Candidate Screening"],["05","Recruitment Coordination"],["06","Successful Placement"]];
export default function HomePage(){return <>
 <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">INTERNATIONAL WORKFORCE SOLUTIONS</div><h1>Connecting European Employers with <span>Qualified International Talent</span></h1><p>Caspian Workforce Group connects European employers with qualified professionals from non-European countries through transparent recruitment, professional coordination and long-term partnerships.</p><div className="hero-actions"><Link href="/employers" className="button button-gold">I’m an Employer</Link><Link href="/job-seekers" className="button button-outline">I’m Looking for a Job</Link></div></div><Globe/></div></section>
 <Section eyebrow="START HERE" title="Choose Your Path" intro="Two clear routes, one trusted international workforce partner."><div className="path-grid"><Link href="/employers" className="path-card"><div className="path-number">01</div><h3>For Employers</h3><p>International workforce solutions tailored to your operational and hiring needs.</p><span>Explore Employer Solutions →</span></Link><Link href="/job-seekers" className="path-card dark"><div className="path-number">02</div><h3>For Job Seekers</h3><p>International career opportunities with trusted employers across Europe.</p><span>Explore Opportunities →</span></Link></div></Section>
 <Section muted eyebrow="ABOUT US" title="Building workforce partnerships that last" intro="Founded in 2022, Caspian Workforce Group helps employers build reliable teams while supporting professionals throughout their international career journey."><Link href="/about" className="text-link">Learn more about us →</Link></Section>
 <Section eyebrow="INDUSTRIES" title="Industries We Support" intro="International recruitment solutions across operational and service sectors."><div className="card-grid">{industries.map(x=><div className="simple-card" key={x}><h3>{x}</h3></div>)}</div></Section>
 <Section muted eyebrow="OUR PROCESS" title="A clear, structured recruitment journey"><div className="process-grid">{process.map(([n,t])=><div className="process-card" key={n}><span>{n}</span><h3>{t}</h3></div>)}</div></Section>
 <section className="cta"><div className="container"><h2>Let’s Start the Conversation</h2><p>Whether you are strengthening your workforce or exploring career opportunities abroad, our team is ready to help.</p><Link href="/contact" className="button button-gold">Contact Our Team</Link></div></section>
 </>}
