import Link from "next/link";import Section from "@/components/Section";
const services=[["International Recruitment","End-to-end international recruitment tailored to employer requirements."],["Workforce Planning","Practical support in defining workforce needs, profiles and hiring priorities."],["Talent Sourcing","Access to qualified international talent through our recruitment network."],["Candidate Screening","Structured initial screening before candidate presentation."],["Recruitment Coordination","Professional coordination and documentation support throughout the hiring process."]];
const industries=["Logistics","Warehousing","Manufacturing","Construction","Hospitality","Agriculture","Food Production","Automotive","Retail","Cleaning Services","Facility Management"];
export default function EmployersPage(){return <><section className="page-hero"><div className="container"><div className="eyebrow">FOR EMPLOYERS</div><h1>International Workforce Solutions for Your Business</h1><p>We help European employers recruit qualified international talent through a structured, transparent and professional process.</p><Link href="/contact" className="button button-gold">Discuss Your Workforce Needs</Link></div></section>
<Section muted eyebrow="CHALLENGES WE SOLVE" title="Helping employers address workforce shortages"><div className="card-grid two">{["Labour shortages","Seasonal demand","High staff turnover","Large-scale hiring needs"].map(x=><div className="simple-card" key={x}><h3>{x}</h3></div>)}</div></Section>
<Section eyebrow="OUR SERVICES" title="Recruitment solutions built around your business"><div className="card-grid two">{services.map(([t,d])=><div className="simple-card" key={t}><h3>{t}</h3><p>{d}</p></div>)}</div></Section>
<Section muted eyebrow="INDUSTRIES" title="Industries We Recruit For"><div className="card-grid">{industries.map(x=><div className="simple-card" key={x}><h3>{x}</h3></div>)}</div></Section>
<Section eyebrow="OUR PROCESS" title="A transparent recruitment journey"><div className="process-grid">{["Consultation","Workforce Planning","Talent Sourcing","Screening","Coordination","Placement"].map((t,i)=><div className="process-card" key={t}><span>0{i+1}</span><h3>{t}</h3></div>)}</div></Section>
<section className="cta"><div className="container"><h2>Ready to strengthen your workforce?</h2><p>Tell us about your hiring needs and our team will contact you to discuss the most suitable recruitment solution.</p><Link href="/contact" className="button button-gold">Start the Conversation</Link></div></section></>}
